import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Baybayin OCR</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Baybayin Optical Character Recognition</h1>

                <p className={styles.description}>
                    An Optical Character Recognition (OCR) system for Baybayin. Trained using the
                    <code className={styles.code}>YOLOv5 Medium</code> model.
                </p>

                <div className={styles.grid}>
                    <a href="/livecam" className={styles.card}>
                        <h2>Use Webcam &rarr;</h2>
                        <p>Use the OCR Model live on your web camera.</p>
                    </a>

                    <a href="/upload" className={styles.card}>
                        <h2>Upload Image &rarr;</h2>
                        <p>Use the OCR Model on an uploaded photo.</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    A project by AMOGUIS, FLORES, MADRID
                    {/* <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span> */}
                </a>
            </footer>
        </div>
    );
};

export default Home;
